#!/bin/bash
#
#######################################
# BREW INSTALL
#######################################

BREWFILE_DIR=$(cd "$(dirname "$0")/.." && pwd)

# Install homebrew & bundle
echo "Installing Homebrew..."

if ! command -v brew &> /dev/null; then
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

	# The installer doesn't update PATH for this already-running script.
	if [ -x /opt/homebrew/bin/brew ]; then
		eval "$(/opt/homebrew/bin/brew shellenv)"
	elif [ -x /usr/local/bin/brew ]; then
		eval "$(/usr/local/bin/brew shellenv)"
	fi
fi

# Update homebrew and package
brew update && brew upgrade

brew bundle --file="${BREWFILE_DIR}/Brewfile"

# Remove outdated versions
brew cleanup
