#!/bin/bash
#
#######################################
# BREW INSTALL
#######################################

BREWFILE_DIR=$(cd "$(dirname "$0")/.." && pwd)

# Install homebrew & bundle
echo "Installing Homebrew..."

if test ! $(which brew); then
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

	brew tap homebrew/bundle
fi

# Update homebrew and package
brew update && brew upgrade

brew bundle --file="${BREWFILE_DIR}/Brewfile"

# Remove outdated versions
brew cleanup
