#!/bin/bash
#
#######################################
# BREW INSTALL
#######################################

# Install homebrew & bundle
echo "Installing Homebrew..."

if test ! $(which brew); then
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

	brew tap homebrew/bundle
fi

sudo chmod -R 755 /usr/local
sudo chown -R $(whoami):admin /usr/local

# Update homebrew and package
brew update & brew upgrade

brew bundle

# Remove outdated versions
brew cleanup
