#!/bin/bash
#
#######################################
# NODE CONFIG
#######################################

# Make sure nvm is installed via brew
brew install nvm

# Load nvm
export NVM_DIR="$HOME/.nvm"
mkdir -p "$NVM_DIR"
NVM_SH="$(brew --prefix nvm)/nvm.sh"
if [ ! -f "$NVM_SH" ]; then
    echo "Could not find nvm.sh at ${NVM_SH}, aborting node setup." >&2
    exit 1
fi
. "$NVM_SH"

# Install and set the latest LTS Node.js as default
nvm install --lts
nvm alias default 'lts/*'
nvm use default

# Install yarn 1.22
npm install --global yarn@1.22

# Make sure npm is present and up to date
npm install --global npm@latest
