#!/bin/bash
#
#######################################
# PYTHON CONFIG
#######################################

# "python" is Homebrew's alias for the latest python@X.Y formula
brew install python
brew upgrade python

PYTHON3="$(brew --prefix)/bin/python3"

# Install pip if it's missing
if ! command -v pip3 &> /dev/null; then
    echo "Installing pip..."
    curl "https://bootstrap.pypa.io/get-pip.py" -o "/tmp/get-pip.py"
    "$PYTHON3" /tmp/get-pip.py
    rm -f /tmp/get-pip.py
fi

# Install and upgrade pip packages to their latest version
"$PYTHON3" -m pip install --upgrade setuptools
"$PYTHON3" -m pip install --upgrade pip

# Clear out pip's cache of previously downloaded packages
"$PYTHON3" -m pip cache purge

# Remove older python@X.Y formulas (and any other leftover formulas) that
# nothing currently installed depends on anymore
brew autoremove
