#!/bin/bash
#
#######################################
# PYTHON CONFIG
#######################################

PYTHON3="$(which python3)"

# Install pip if it's missing
if ! command -v pip3 &> /dev/null; then
    echo "Installing pip..."
    curl "https://bootstrap.pypa.io/get-pip.py" -o "/tmp/get-pip.py"
    "$PYTHON3" /tmp/get-pip.py
    rm -f /tmp/get-pip.py
fi

# Install and upgrade pip packages
"$PYTHON3" -m pip install --upgrade setuptools
"$PYTHON3" -m pip install --upgrade pip
