#!/bin/bash
#
#######################################
# PYTHON CONFIG
#######################################

# Set python3 as default
alias python=$(which python3)

# Install pip and pip dependencies
if [[ pip != "pip" ]]; then
    echo "Installing pip..."
    curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
    python get-pip.py
fi

# Set pip3 as default
port select --set pip pip3

# Install and upgrade pip packages
python -m pip install --upgrade setuptools
python -m pip install --upgrade pip

python -m pip install pandas
python -m pip install virtualenv
python -m pip install awscli
python -m pip install numpy
python -m pip install requests
python -m pip install pytest
