#!/bin/bash
#
#######################################
# OSX PREFERENCES
#######################################

PROJECTS_DIR=~/Documents/Projects
SCREENSHOT_DIR=~/Screenshots

# Close any open System Preferences panes
osascript -e 'tell application "System Preferences" to quit'

# Set software update OFF to avoid conflicts
sudo softwareupdate --schedule OFF

#######################################
# Launchpad
#######################################
# Set minimize effect to scale
defaults write com.apple.dock mineffect -string scale

#######################################
# Trackpad
#######################################
# Disable "natural" scrolling
defaults write NSGlobalDomain com.apple.swipescrolldirection -bool false

#######################################
# iTerm 2
#######################################
/usr/libexec/PlistBuddy -c "Delete :'New Bookmarks':0:'Custom Directory'" ~/Library/Preferences/com.googlecode.iterm2.plist
/usr/libexec/PlistBuddy -c "Add :'New Bookmarks':0:'Custom Directory' string Recycle" ~/Library/Preferences/com.googlecode.iterm2.plist

#######################################
# Default browser
#######################################
# Set Google Chrome as the default browser for http/https links and html files
if command -v duti &> /dev/null && [ -d "/Applications/Google Chrome.app" ]; then
	duti -s com.google.Chrome http
	duti -s com.google.Chrome https
	duti -s com.google.Chrome public.html
	duti -s com.google.Chrome public.xhtml
fi

#######################################
# Finder
#######################################

# Disable warning before emptying the trash
defaults write com.apple.finder WarnOnEmptyTrash -bool false

# Empty trash securely by default
defaults write com.apple.finder EmptyTrashSecurely -bool true

# Show library folder
chflags nohidden ~/Library && xattr -d com.apple.FinderInfo ~/Library

# Show hidden files
defaults write com.apple.finder AppleShowAllFiles -bool true

# Show path bar and status bar
defaults write com.apple.finder ShowPathbar -bool true
defaults write com.apple.finder ShowStatusBar -bool true

# Use list view in all Finder windows by default
defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"

#######################################
# Dock
#######################################

# Auto-hide the Dock
defaults write com.apple.dock autohide -bool true

# Smaller icon size
defaults write com.apple.dock tilesize -int 36

# Don't show recently used apps
defaults write com.apple.dock show-recents -bool false

#######################################
# Menu bar
#######################################

# Show battery percentage
defaults -currentHost write com.apple.controlcenter BatteryShowPercentage -bool true

# Create path for my projects
mkdir -p $PROJECTS_DIR

# Create path to save screenshots
mkdir -p $SCREENSHOT_DIR
defaults write com.apple.screencapture location $SCREENSHOT_DIR

#######################################
# Kill affected applications
#######################################
killall Finder
killall Dock
  
sudo softwareupdate --schedule ON
